"""Canonical civic-demand schema (PRD §21, §31) and structured AI output schemas (PRD §33).

JSON Schema copies live in `ai/schemas/` and `data/schemas/` (generated by `app.export_schemas`).
"""
from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field

Category = Literal[
    "roads_bridges", "drinking_water", "sanitation", "electricity", "health_facility",
    "school_education", "digital_connectivity", "housing", "irrigation", "public_transport", "other",
]
CATEGORIES: tuple[str, ...] = Category.__args__  # type: ignore[attr-defined]
Urgency = Literal["low", "medium", "high", "critical"]
Language = Literal["en", "hi", "te"]
LANGUAGES: tuple[str, ...] = Language.__args__  # type: ignore[attr-defined]
ClusterStatus = Literal["Clustered", "Under Review", "Recommended", "Sanctioned", "Completed"]
RequestStatus = Literal[
    "Received", "Understood", "Needs Clarification", "Clustered", "Under Review", "Recommended",
    "Sanctioned", "Completed",
]


# ----------------------------------------------------------------------------------------------
# Structured AI outputs (Gemini response_schema). Keep these free of dict/Any for schema support.
# ----------------------------------------------------------------------------------------------
class LocationMention(BaseModel):
    text: str = Field(description="Place name exactly as written or spoken by the citizen")
    type: Literal["village", "ward", "block", "mandal", "district", "city", "landmark", "other"]


class RequestExtraction(BaseModel):
    """Gemini request-understanding output (prompt: ai/prompts/extract_v1.md)."""

    category: Category
    sub_category: str
    summary_en: str
    location_mentions: list[LocationMention]
    urgency: Urgency
    urgency_reason: str
    est_beneficiaries: int | None = Field(description="Only if a number is explicitly stated; else null")
    vulnerable_groups: list[str]
    seasonality: str | None
    sentiment: float = Field(ge=-1, le=1)
    confidence: float = Field(ge=0, le=1)
    missing_information: list[str]
    requires_clarification: bool
    clarification_question: str | None = None


class DataEvidence(BaseModel):
    claim: str
    field: str
    value: str
    source: str
    year: str


class EvidenceBrief(BaseModel):
    """Gemini evidence-brief output (prompt: ai/prompts/evidence_brief_v1.md)."""

    title: str
    summary: str
    demand_evidence: list[str]
    data_evidence: list[DataEvidence]
    investment_context: list[str]
    estimated_beneficiaries: int | None
    beneficiaries_basis: str
    uncertainties: list[str]
    next_step: str
    confidence: float = Field(ge=0, le=1)


class Transcript(BaseModel):
    """Gemini audio-transcription fallback output (prompt: ai/prompts/transcribe_v1.md)."""

    transcript: str
    language: Language


class Translation(BaseModel):
    """Gemini translation fallback output (prompt: ai/prompts/translate_v1.md)."""

    text_en: str
    detected_language: Language


# ----------------------------------------------------------------------------------------------
# Canonical entities
# ----------------------------------------------------------------------------------------------
class Provenance(BaseModel):
    model_name: str
    model_version: str
    prompt_version: str
    generated_at: datetime
    mode: Literal["real", "demo"] = "real"
    note: str | None = None


class AdminUnit(BaseModel):
    """Lowest mapped administrative unit (village / habitation / ward) with parents."""

    lgd_code: str
    code_system: str = "sample-lgd-style"
    name: str
    name_local: str | None = None
    level: str
    state: str
    district_code: str
    district_name: str
    block_code: str
    block_name: str
    lat: float
    lng: float
    h3_cell: str


class Indicator(BaseModel):
    lgd_code: str
    indicator_name: str
    value: float | bool
    year: int
    geographic_level: str
    source: str
    definition: str | None = None
    is_sample: bool = True


class Investment(BaseModel):
    project_id: str
    scheme: str
    title: str
    category: Category
    lgd_codes: list[str]
    block_code: str | None
    status: Literal["proposed", "sanctioned", "ongoing", "completed"]
    sanctioned_amount_inr: float
    start_date: str
    population_covered: int
    source: str
    is_sample: bool = True


class LocationResolution(BaseModel):
    resolved: bool
    lgd_state: str | None = None
    lgd_district: str | None = None
    lgd_block: str | None = None
    lgd_unit: str | None = None
    unit_name: str | None = None
    block_name: str | None = None
    district_name: str | None = None
    h3_cell: str | None = None
    lat: float | None = None
    lng: float | None = None
    method: Literal["pin", "exact_match", "fuzzy_match", "geocoded", "clarified", "unresolved", "ambiguous"]
    confidence: float = 0.0
    candidates: list[dict] = []
    clarification_question: str | None = None


class CitizenRequest(BaseModel):
    request_id: str
    citizen_id: str
    channel: str
    language: str
    text_original: str
    text_en: str
    audio_url: str | None = None
    photo_url: str | None = None
    category: str
    sub_category: str | None = None
    summary_en: str
    urgency: str
    urgency_reason: str | None = None
    est_beneficiaries: int | None = None
    vulnerable_groups: list[str] = []
    seasonality: str | None = None
    sentiment: float = 0.0
    confidence: float = 0.0
    missing_information: list[str] = []
    state: str | None = None
    lgd_district: str | None = None
    lgd_block: str | None = None
    lgd_unit: str | None = None
    h3_cell: str | None = None
    resolution_method: str | None = None
    resolution_confidence: float | None = None
    cluster_id: str | None = None
    status: str = "Received"
    created_at: datetime
    model_name: str
    model_version: str
    prompt_version: str
    is_synthetic: bool = False


class DemandCluster(BaseModel):
    cluster_id: str
    state: str
    category: str
    sub_category: str | None = None
    lgd_district: str
    lgd_block: str
    lgd_units: list[str]
    h3_cells: list[str] = []
    request_count: int = 0
    unique_citizens: int = 0
    first_seen: datetime | None = None
    last_seen: datetime | None = None
    summary: str
    status: str = "Clustered"
    is_synthetic: bool = False


class Weights(BaseModel):
    """Policy lens (PRD §15). Percent weights; investment is subtracted."""

    demand: float = Field(30, ge=0, le=100)
    infra_gap: float = Field(30, ge=0, le=100)
    vulnerability: float = Field(20, ge=0, le=100)
    trend: float = Field(10, ge=0, le=100)
    investment: float = Field(10, ge=0, le=100)


class FactorScore(BaseModel):
    factor: str
    label: str
    raw: float | None
    normalised: float
    weight: float
    contribution: float
    explanation: str
    sources: list[str] = []


class ScoredCluster(BaseModel):
    recommendation_id: str
    cluster_id: str
    rank: int
    default_rank: int | None = None
    priority_score: float
    band: Literal["High", "Medium", "Low"]
    breakdown: list[FactorScore]
    weights_used: Weights
